application: gcs-blobstore
version: 2
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: blob_upload.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest